.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPROUT" "1" "March 2015" "" ""
.
.SH "NAME"
\fBsprout\fR \- simple project templating
.
.SH "SYNOPSIS"
\fBsprout\fR add name src
.
.br
\fBsprout\fR remove name
.
.br
\fBsprout\fR list
.
.br
\fBsprout\fR init name target
.
.SH "DESCRIPTION"
Sprout helps with templating for new projects\. It allows management of different project templates that can be copied quickly when starting fresh, and provides an interface to customize the new projects as specified by the template author\.
.
.P
Underlined parameters are required, non\-underlined optional\.
.
.SH "ADD"
\fBsprout add [\-h] [\-v] name src\fR
.
.P
Adds a template to your repertoire from \fBsrc\fR as \fBname\fR\. Name represents how you would like the template to be named within sprout\. You are required to add a \fItemplate\fR which can be either a clone url or a path to a local template\. If no name is provided, sprout will use the last piece of the template as the name\.
.
.SS "OPTIONS"
\fB\-v\fR, \fB\-\-verbose\fR Run in verbose mode\.
.
.SH "REMOVE"
\fBsprout remove [\-h] [\-v] name\fR: Removes the template with the specified \fBname\fR from sprout\.
.
.SS "OPTIONS"
\fB\-v\fR, \fB\-\-verbose\fR Run in verbose mode\.
.
.SH "LIST"
\fBlist\fR
.
.P
list all the templates that have been added to sprout\.
.
.SH "INIT"
\fBsprout init [\-h] [\-l [LOCALS [LOCALS \.\.\.]]] [\-t TAG] [\-b BRANCH] [\-c CONFIG] [\-v] name target\fR
.
.P
Initializes the template with the given \fBname\fR at the given \fBtarget\fR\. If no path is provided it will create a new folder with the same name as the template in the current working directory\. If there already is one, it will throw an error\.
.
.SS "OPTIONS"
\fB\-l [LOCALS [LOCALS \.\.\.]]\fR, \fB\-\-locals [LOCALS [LOCALS \.\.\.]]\fR: Pass locals as options which will override the prompts set in your templates\. Locals are passed to the CLI like so: \fB\-l key1=value1 key2=\'value2\'\fR
.
.P
\fB\-t TAG\fR, \fB\-\-tag TAG\fR: Pass a git tag to generate the template from\.
.
.P
\fB\-b BRANCH\fR, \fB\-\-tag branch\fR: Pass a git branch to generate the template from\.
.
.P
\fB\-c CONFIG\fR, \fB\-\-config CONFIG\fR: Pass a JSON or yaml file to pre\-define a large set of values\.
.
.P
\fB\-v\fR, \fB\-\-verbose\fR Run in verbose mode\.
.
.SH "HELP"
\fB\-\-help\fR, \fB\-h\fR
.
.P
usage docs, can be run for every sub\-command as well for command\-specific docs\.
.
.SH "SOURCE"
Full source and docs can be found at \fIhttp://github\.com/carrot/sprout\fR\.
